/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cocina.glb -o src/components/models/Cocina.tsx 
Author: sutarabrenda (https://sketchfab.com/sutarabrenda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kitchen-l-shaped-with-island-e32dbd7d7365453082bce4b9948803d7
Title: Kitchen L-Shaped with Island
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { ComponentPropsWithoutRef } from "react";

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh | THREE.LineSegments>;
  materials: Record<string, THREE.Material>;
};

type GroupProps = ComponentPropsWithoutRef<"group">;

export function Cocina(props: GroupProps) {
  const { nodes, materials } = useGLTF(
    "/models/cocina.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={(nodes.Material63 as THREE.Mesh).geometry}
          material={materials.Material63}
        />
        <mesh
          geometry={(nodes.Material35 as THREE.Mesh).geometry}
          material={materials.Material35}
        />
        <mesh
          geometry={(nodes.Material53 as THREE.Mesh).geometry}
          material={materials.Material53}
        />
        <mesh
          geometry={(nodes.Material66 as THREE.Mesh).geometry}
          material={materials.Material66}
        />
        <mesh
          geometry={(nodes.Material41 as THREE.Mesh).geometry}
          material={materials.Material41}
        />
        <mesh
          geometry={(nodes.Material24 as THREE.Mesh).geometry}
          material={materials.Material24}
        />
        <mesh
          geometry={(nodes.Material32 as THREE.Mesh).geometry}
          material={materials.Material32}
        />
        <mesh
          geometry={(nodes.Material19 as THREE.Mesh).geometry}
          material={materials.Material19}
        />
        <mesh
          geometry={(nodes.Material11 as THREE.Mesh).geometry}
          material={materials.Material11}
        />
        <mesh
          geometry={(nodes.Material17 as THREE.Mesh).geometry}
          material={materials.Material17}
        />
        <mesh
          geometry={(nodes.Material16 as THREE.Mesh).geometry}
          material={materials.Material16}
        />
        <mesh
          geometry={(nodes.Material83 as THREE.Mesh).geometry}
          material={materials.Material83}
        />
        <mesh
          geometry={(nodes.Material93 as THREE.Mesh).geometry}
          material={materials.Material93}
        />
        <mesh
          geometry={(nodes.Material94 as THREE.Mesh).geometry}
          material={materials.Material94}
        />
        <mesh
          geometry={(nodes.Material96 as THREE.Mesh).geometry}
          material={materials.Material96}
        />
        <mesh
          geometry={(nodes.Material95 as THREE.Mesh).geometry}
          material={materials.Material95}
        />
        <mesh
          geometry={(nodes.Material108 as THREE.Mesh).geometry}
          material={materials.Material108}
        />
        <mesh
          geometry={(nodes.Material31 as THREE.Mesh).geometry}
          material={materials.Material31}
        />
        <mesh
          geometry={(nodes.Material31_1 as THREE.Mesh).geometry}
          material={materials.Material31}
        />
        <mesh
          geometry={(nodes.Material2 as THREE.Mesh).geometry}
          material={materials.Material2}
        />
        <mesh
          geometry={(nodes.Material13 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_1 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_2 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_3 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_4 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_5 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_6 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_7 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_8 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_9 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_10 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material13_11 as THREE.Mesh).geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={(nodes.Material70 as THREE.Mesh).geometry}
          material={materials.Material70}
        />
        <mesh
          geometry={(nodes.Material18 as THREE.Mesh).geometry}
          material={materials.Material18}
        />
        <mesh
          geometry={(nodes.Material3 as THREE.Mesh).geometry}
          material={materials.Material3}
        />
        <mesh
          geometry={(nodes.Material51 as THREE.Mesh).geometry}
          material={materials.Material51}
        />
        <mesh
          geometry={(nodes.Material52 as THREE.Mesh).geometry}
          material={materials.Material52}
        />
        <mesh
          geometry={(nodes.Material20 as THREE.Mesh).geometry}
          material={materials.Material20}
        />
        <mesh
          geometry={(nodes.Material20_1 as THREE.Mesh).geometry}
          material={materials.Material20}
        />
        <mesh
          geometry={(nodes.Material20_2 as THREE.Mesh).geometry}
          material={materials.Material20}
        />
        <mesh
          geometry={(nodes.Material20_3 as THREE.Mesh).geometry}
          material={materials.Material20}
        />
        <mesh
          geometry={(nodes.Material20_4 as THREE.Mesh).geometry}
          material={materials.Material20}
        />
        <mesh
          geometry={(nodes.Material20_5 as THREE.Mesh).geometry}
          material={materials.Material20}
        />
        <mesh
          geometry={(nodes.Material25 as THREE.Mesh).geometry}
          material={materials.Material25}
        />
        <mesh
          geometry={(nodes.Material6 as THREE.Mesh).geometry}
          material={materials.Material6}
        />
        <mesh
          geometry={(nodes.Material30 as THREE.Mesh).geometry}
          material={materials.Material30}
        />
        <mesh
          geometry={(nodes.Material30_1 as THREE.Mesh).geometry}
          material={materials.Material30}
        />
        <mesh
          geometry={(nodes.Material30_2 as THREE.Mesh).geometry}
          material={materials.Material30}
        />
        <mesh
          geometry={(nodes.Material30_3 as THREE.Mesh).geometry}
          material={materials.Material30}
        />
        <mesh
          geometry={(nodes.Material30_4 as THREE.Mesh).geometry}
          material={materials.Material30}
        />
        <mesh
          geometry={(nodes.Material30_5 as THREE.Mesh).geometry}
          material={materials.Material30}
        />
        <mesh
          geometry={(nodes.Material30_6 as THREE.Mesh).geometry}
          material={materials.Material30}
        />
        <mesh
          geometry={(nodes.Material30_7 as THREE.Mesh).geometry}
          material={materials.Material30}
        />
        <mesh
          geometry={(nodes.Material10 as THREE.Mesh).geometry}
          material={materials.Material10}
        />
        <mesh
          geometry={(nodes.Material40 as THREE.Mesh).geometry}
          material={materials.Material40}
        />
        <lineSegments
          geometry={(nodes.Material110 as THREE.LineSegments).geometry}
          material={materials.Material110}
        />
        <mesh
          geometry={(nodes.Material54 as THREE.Mesh).geometry}
          material={materials.Material54}
        />
        <mesh
          geometry={(nodes.Material54_1 as THREE.Mesh).geometry}
          material={materials.Material54}
        />
        <mesh
          geometry={(nodes.Material54_2 as THREE.Mesh).geometry}
          material={materials.Material54}
        />
        <mesh
          geometry={(nodes.Material26 as THREE.Mesh).geometry}
          material={materials.Material26}
        />
        <mesh
          geometry={(nodes.Material7 as THREE.Mesh).geometry}
          material={materials.Material7}
        />
        <mesh
          geometry={(nodes.Material43 as THREE.Mesh).geometry}
          material={materials.Material43}
        />
        <mesh
          geometry={(nodes.Material28 as THREE.Mesh).geometry}
          material={materials.Material28}
        />
        <mesh
          geometry={(nodes.Material102 as THREE.Mesh).geometry}
          material={materials.Material102}
        />
        <mesh
          geometry={(nodes.Material67 as THREE.Mesh).geometry}
          material={materials.Material67}
        />
        <mesh
          geometry={(nodes.Material22 as THREE.Mesh).geometry}
          material={materials.Material22}
        />
        <mesh
          geometry={(nodes.Material50 as THREE.Mesh).geometry}
          material={materials.Material50}
        />
        <mesh
          geometry={(nodes.Material33 as THREE.Mesh).geometry}
          material={materials.Material33}
        />
        <mesh
          geometry={(nodes.Material5 as THREE.Mesh).geometry}
          material={materials.Material5}
        />
        <mesh
          geometry={(nodes.Material4 as THREE.Mesh).geometry}
          material={materials.Material4}
        />
        <mesh
          geometry={(nodes.Material107 as THREE.Mesh).geometry}
          material={materials.Material107}
        />
        <mesh
          geometry={(nodes.Material107_1 as THREE.Mesh).geometry}
          material={materials.Material107}
        />
        <mesh
          geometry={(nodes.Material109 as THREE.Mesh).geometry}
          material={materials.Material109}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/cocina.glb");
