/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sutarabrenda (https://sketchfab.com/sutarabrenda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/detalle-de-entrepiso-liviano-en-archicad-c65f3e0c6f5f409588e8669cdd0e8c2c
Title: Detalle de Entrepiso Liviano en Archicad
*/

import { useGLTF } from "@react-three/drei";

type GLTFResult = {
  nodes: Record<string, any>;
  materials: Record<string, any>;
};

export function DetalleEncuentro(
  props: React.ComponentPropsWithoutRef<"group">
) {
  const { nodes, materials } = useGLTF(
    "models/detalle_de_entrepiso_liviano_en_archicad.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 1.4]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material11.geometry}
          material={materials.Material11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material16.geometry}
          material={materials.Material16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material12.geometry}
          material={materials.Material12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material14.geometry}
          material={materials.Material14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material6.geometry}
          material={materials.Material6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material15.geometry}
          material={materials.Material15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material15_1.geometry}
          material={materials.Material15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material15_2.geometry}
          material={materials.Material15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material15_3.geometry}
          material={materials.Material15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material15_4.geometry}
          material={materials.Material15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material15_5.geometry}
          material={materials.Material15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material4.geometry}
          material={materials.Material4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material4_1.geometry}
          material={materials.Material4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material8.geometry}
          material={materials.Material8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material8_1.geometry}
          material={materials.Material8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material8_2.geometry}
          material={materials.Material8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material8_3.geometry}
          material={materials.Material8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material8_4.geometry}
          material={materials.Material8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material8_5.geometry}
          material={materials.Material8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material9.geometry}
          material={materials.Material9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material28.geometry}
          material={materials.Material28}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material17.geometry}
          material={materials.Material17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material29.geometry}
          material={materials.Material29}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material22.geometry}
          material={materials.Material22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.Material3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material5.geometry}
          material={materials.Material5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material27.geometry}
          material={materials.Material27}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/detalle_de_entrepiso_liviano_en_archicad.glb");
